[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  version = "^1.3.7"
  name = "gopkg.in/alecthomas/kingpin.v1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.34"
