

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/goamz/goamz"

[[constraint]]
  version = "^1.3.7"
  name = "gopkg.in/alecthomas/kingpin.v1"
